name: thrive_futurama
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Network
  chopper: 6.1.1
  built_value: ^8.4.4
  built_collection: ^5.1.1
  connectivity_plus: ^3.0.4

  # Redux
  redux: ^5.0.0
  flutter_redux: ^0.10.0

  # Navigation
  go_router: ^6.5.6

  # UI
  responsive_builder: ^0.6.4

  # Utils
  provider: ^6.0.5
  get_it: ^7.2.0
  equatable: ^2.0.5
  logger: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0

flutter:
  uses-material-design: true
